### ISSUE TITLE
U2F Testing / Passwordless Console

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#1103]
### Policy

- [x] configuration of 2FA/ MFA providers: each provider must only be set once
- [x] configuration of identity providers: each provider must only be set once
- [x] 2FA/MFA can be configured without creating a custom policy, resulting in error from backend
- [x] enable passwordless configuration

### (Self) Management

- [x] MFA attribute is not shown
- [x] U2F cannot be deleted on other users (missing user id param)
- [x] self management: cannot create u2f when otp is set up (even if not ready, problem seams only to occur when loading the whole page)
- [ ] cannot register multiple u2f tokens:
![image](https://user-images.githubusercontent.com/9405495/102088161-d0e9ff00-3e1a-11eb-9f12-10615fbf6737.png)
- [ ] enable passwordless registration / management (like u2f)

## Backend

- [x] RP ID for U2F is wrong -> U2F Registration not possible in Console (#1104)
- [X] as soon as 'u2f with pin' is configured in policy, there's a second u2f provider at login (#1105)
- [x] missing event translations (#1105)
- [x] add missing passwordless functions in auth and mgmt api (#1105)
