### ISSUE TITLE
v1.0 backend issues

### ISSUE THREAD

**Issue by peintnermax** [caos/zitadel#1410]
- [X] getMyUser returns human undefined in its userobject -> fixed by #1413
- [x] getmyorg returns grpc 14 -> craches in ui because of listorgmembers
- [x] same for listorgmembers -> will be fixed by #1413
- [x] same for listorgdomains -> craches in ui because of listorgmembers
- [x] same for getPasswordComplexityPolicy -> cannot reproduce 
- [x] Zitadel project has no creation date (undefined) -> will be fixed by #1413
- [ ] project (zitadel) returnes no apps -> cannot reproduce 
- [x] listusers returnes empty list -> fixed by #1413
- [x] can't SetUpOrg -> fixed by #1413
