### ISSUE TITLE
v1.0 backend issues

### ISSUE THREAD

**Issue by peintnermax** [caos/zitadel#1425]
- [x] on create oidcapp -> get project not found + Message=Porject not found - typo in error message -> #1429
- [x] same for apiApp -> #1429
- [x] projects gets added to all organizations -> #1429
- [x] project not found on addprojectgrant -> #1429
- [x] same on addrole -> #1429
- [x] something's strange with policies.. policy returns data of iam policy but has isDefault == false + can't be updated then Errors.Org.PasswordComplexityPolicy.NotFound -> #1429
- [x] cant update phone (mgmt) -> #1429
- [x] notification doesn't work (initial mail not sent, cant resend code) -> error in login Errors.User.Email.NotFound (COMMAND-G8dh3)
- [x] add auth factor (mgmt) -> user not found -> #1429

**Comment by peintnermax** [comment]
- [ ] updateHumanProfile remove required displayname (isnt that calculated?) error invalid UpdateHumanProfileRequest.DisplayName: value length must be between 1 and 200 runes, inclusive

**Comment by fgerschwiler** [comment]
- [ ] get iam meber roles doesnt return roles

**Comment by peintnermax** [comment]
- [ ] addpasswordless doesnt work. returns {id: "", publicKey: ""}

**Comment by peintnermax** [comment]
@fgerschwiler  addmymultifactoru2f response looks like this: empty public key but stringified JSON in id
<img width="774" alt="Bildschirmfoto 2021-03-23 um 08 56 01" src="https://user-images.githubusercontent.com/10165752/112112300-a34ce880-8bb5-11eb-887c-674e9b2c458f.png">

**Comment by fgerschwiler** [comment]
![Uploading image.png…]()

**Comment by fgerschwiler** [comment]
![image](https://user-images.githubusercontent.com/38692350/112495781-7e5aa000-8d84-11eb-811b-4109a28c96e9.png)
