### ISSUE TITLE
Frontend Bugs

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#205]
MenuBar:
- [x] Sometimes my org context switches
- [x] Add new account --> change to login with another account
- [x] If user has no rigths use user.resourceowner for org-header

Personal Information:
- [x] Can not change Gender and Language
- [x] Change Password shown Password policy should match stored Password Policy (GetPasswordpolicyForOrg)
- [x] If no existing PhoneNumber I cant add one
- [x] If no existing Adrres I cant add
- [x] On click "send code" (Email/Phone) row is empty
- [x] If userstate initial show resend initial pw
- [x] Add OTP doesn't show QR-Code
- [x] Remove DisplayName from Create and Update
- [x] Do no fill username automatically with email (new we have normally no email as username)
- [x] Read OrgIam Policy (AdminService) if user_login_must_be_domain email in username is not allowed
- [x] I set up otp during login, but it‘s not listed in mfa ([see error message during load](https://github.com/caos/zitadel/issues/205#issuecomment-645516495))
- [x] Maybe Login names should be in Profile as first field. Its the most important info for the user
- [x] PasswordPolicy Pipe doesn't work correct
- [x] Remove otp doesnt work

Users:
- [ ] Cant add user grant (moved to #291)
- [x] Show loginnames
- [x] UserGrant Add, Roles are not required field

Orgs:
- [x] Add Org missing (Only for iam admins)
- [x] new domain field should be cleard after add
- [x] on create org for user username is missing
- [x] install on policy doesn't make sense
- [x] complexity policy min length + and - wrong, pluss should be on right side
- [x] Remove Domain Verifications things

Projects:
- [x] Zitadel Project should not be changable
- [x] Contributers not shown
- [x] Cant add Project Member
- [x] I get the possibility to add new project, even if i dont have this permission (my user is project owner of a specifig project)
- [x] On overview i would remove the info, (active, inactive) its more confusing than helpful
- [x] On Overview tile at the bottom left of a project doesnt make anythiing
- [x] On Granted Projects show name of org
- [x] Remvoe type
- [ ] Project Grant Add, Roles are not required field

Apps:
- [ ] OIDC Apps to complicated to configure for users?!  (moved to #275 )
- [x] Active Inactive is strange toggle in toggle?

ProjectRole:
- [x] Remove Name (We changed attribute name to key)
- [x] On Add Role, add another role, something is strange
- [x] Can't add new Role (Key is required)
- [x] Only Key is required field

Admin:
- [x] We have a new Policy Org IamPolicy, IamAdmins are allowed to edit, show, remove it  (iam.policy.read, iam.policy.write...)

Changes:
- [x] The times shown with the changes differ from the time served by the `API` this looks like a UI Problem 

General:
- [x] I get the message no matching permissions found often, this should not be shown
- [x] On changes it would be nice to see who was the editor
- [ ] [translation encoding](https://github.com/caos/zitadel/issues/205#issuecomment-647912688): protocol states message shall be urlDecoded, using the message as is on error: https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/PROTOCOL-HTTP2.md (moved to #291 )

Iam:
- [x] Iam Admin should be able to add/change/remove Iam Members

**Comment by livio-a** [comment]
![image](https://user-images.githubusercontent.com/9405495/84930265-4b86cb80-b0d1-11ea-9308-3a0ae5ea88a6.png)

**Comment by livio-a** [comment]
Encoding of translations is wrong.
If i want to change my password in the profile section and send a wrong password as `current password` the enconding of the returned error message is wrong.
wrong password: 
![image](https://user-images.githubusercontent.com/27845747/85289770-3aa2d500-b498-11ea-88d5-24f8063a77ee.png)
error message:
![image](https://user-images.githubusercontent.com/27845747/85289855-5b6b2a80-b498-11ea-9141-acc3dab59bad.png)
![image](https://user-images.githubusercontent.com/27845747/85289950-7b9ae980-b498-11ea-8c91-9ba05838ead5.png)

_Originally posted by @adlerhurst in https://github.com/caos/zitadel/issues/206#issuecomment-647501074_
