### ISSUE TITLE
Testprotokoll

### ISSUE THREAD

**Issue by thesephirot** [caos/zitadel#238]
# Frontend: #
#### NEW REGISTERED USER CONTEXT ######
- [x] language is set to german, password policy hints are in english
- [ ] 'no matching permissions found' "popup" bei jedem klick (moved to #291 )
- [x] when adding a mailaddress via manager function, the search is loaded and keepy searching, but no entry is shown (instead of "not found" after a while)
<img width="400" alt="Screenshot 2020-06-18 at 08 52 05" src="https://user-images.githubusercontent.com/47860090/84987727-0306f680-b141-11ea-9976-5776d5813638.png">

- [x] my mfa is set, but not shown as "already done"
<img width="960" alt="Screenshot 2020-06-18 at 08 53 59" src="https://user-images.githubusercontent.com/47860090/84987893-524d2700-b141-11ea-935b-59d8e02346c7.png">

- [x] adding internal or external users does not show a working "add" button
<img width="399" alt="Screenshot 2020-06-18 at 08 58 56" src="https://user-images.githubusercontent.com/47860090/84988375-31390600-b142-11ea-9aa5-ece060b5d824.png">

- [x] AGB und Impressum verweisen auf den gleichen link
(https://caos.ch/impressum/)
<img width="151" alt="Screenshot 2020-06-18 at 09 01 41" src="https://user-images.githubusercontent.com/47860090/84988521-70675700-b142-11ea-8819-66bf3353fb52.png">

- [x] history on the right side of the page is shown after initial login of new user. afterwards it ist not shown anymore. it is shown when creating a new project though, but empty.

- [x] user button in the right upper corner has no function 
<img width="90" alt="Screenshot 2020-06-18 at 09 17 02" src="https://user-images.githubusercontent.com/47860090/84989808-8544ea00-b144-11ea-9896-dda049d90828.png">

- [x] red button shows "IAM user" on hover,.. what should that mean?
<img width="121" alt="Screenshot 2020-06-18 at 09 18 02" src="https://user-images.githubusercontent.com/47860090/84989903-ac032080-b144-11ea-9347-c279fb8de607.png">

#### ADMIN USER CONTEXT ####
- [x] adding a Manager does not have an effect, there is no manager shown nore a change in activities (actually I added 2 managers)
<img width="364" alt="Screenshot 2020-06-18 at 09 43 05" src="https://user-images.githubusercontent.com/47860090/84992512-487af200-b148-11ea-9661-c4d7b67897bf.png">
<img width="423" alt="Screenshot 2020-06-18 at 09 44 28" src="https://user-images.githubusercontent.com/47860090/84992535-53358700-b148-11ea-866a-e3e0876957d6.png">

-  [ ] Global  was soll mir dieser Text sagen? ich versteh ihn nicht. (moved to #296)
<img width="1589" alt="Screenshot 2020-06-18 at 09 47 18" src="https://user-images.githubusercontent.com/47860090/84992859-c3440d00-b148-11ea-88a8-23a70c33f8aa.png">

- [x] deleting a domain shows a popup "removed" at the bottom, but a page reload is needed until the domain disappears 
<img width="1237" alt="Screenshot 2020-06-18 at 10 23 06" src="https://user-images.githubusercontent.com/47860090/84996876-24baaa80-b14e-11ea-8b16-06319aa0d4c9.png">

- [x] text description at projectoverview ist sloppy german
<img width="1048" alt="Screenshot 2020-06-18 at 10 53 16" src="https://user-images.githubusercontent.com/47860090/85000039-2b4b2100-b152-11ea-947b-e4ccf9918930.png">

- [x] type "im Besitz"... is a status to me, not a type
<img width="322" alt="Screenshot 2020-06-18 at 11 00 49" src="https://user-images.githubusercontent.com/47860090/85000689-0a370000-b153-11ea-8caa-197aabd7aaa5.png">

-  [x] "wenn Sie ein Projekt nicht finden können" would be more precise
<img width="1057" alt="Screenshot 2020-06-18 at 11 10 36" src="https://user-images.githubusercontent.com/47860090/85001815-6e0df880-b154-11ea-9806-18a74348f3db.png">

- [x] adding an an application and filling out the fields leads to an error:
(this is due to the tickboxes of response/grant/app types, I just selected one each)
<img width="1172" alt="Screenshot 2020-06-18 at 12 45 49" src="https://user-images.githubusercontent.com/47860090/85011423-cc8da380-b161-11ea-99c2-8aa34c6e468e.png">

- [x] (application) -> secret neu generieren bringt fehler:
<img width="1149" alt="Screenshot 2020-06-18 at 12 58 28" src="https://user-images.githubusercontent.com/47860090/85012663-a5d06c80-b163-11ea-90b9-f9907e5d133e.png">

- [x] Aktivität @ Global sind mal auf-, mal abwärts sortiert
<img width="431" alt="Screenshot 2020-06-18 at 13 03 35" src="https://user-images.githubusercontent.com/47860090/85013059-40c94680-b164-11ea-9fcb-aa3603913405.png">
<img width="415" alt="Screenshot 2020-06-18 at 13 05 58" src="https://user-images.githubusercontent.com/47860090/85013203-7c641080-b164-11ea-979c-a770fd95feaf.png">

- [ ] Projektstatus "aktiv". wie würde ich denn ein Projekt inaktiv setzen? was bedeutet "aktiv" ?
bei multiliste, welche Projekte sind aktiv? (moved to #275 )
<img width="475" alt="Screenshot 2020-06-18 at 13 08 51" src="https://user-images.githubusercontent.com/47860090/85013527-02805700-b165-11ea-8573-c584504d1dcc.png">

- [x] Projekt Übersicht - Grants "+" button legt ein neues Projekt an obwohl direkt darüber der "add new project button" ist- 
<img width="1225" alt="Screenshot 2020-06-18 at 13 11 24" src="https://user-images.githubusercontent.com/47860090/85013694-4ffcc400-b165-11ea-9eea-b353b5f5f1de.png">

- [x] generell, sehr viele englische Begriffe (add, remove, change... ) obwohl Deutsch als Sprache ausgewählt ist (should be done with #275 , pls add specific points to list)

- [x] Userkontext wechsel (button rechts oben mit männchen), hat bei mir genau 1x funktioniert nach einem logout. sonst gar nicht (button hat löst keine aktion aus)

# Login: #
#### NEW REGISTERED USER CONTEXT ######
- [x] qr code color needs to be inverted manualy when using fair/bright theme

# Backend: # 
#### NEW REGISTERED USER CONTEXT ######
- [x] creating a new project overwrites the existing one (My Zitadel Permissions only returns permissions for one project)
<img width="774" alt="Screenshot 2020-06-18 at 09 06 38" src="https://user-images.githubusercontent.com/47860090/84988931-216df180-b143-11ea-97b3-f910e8d6dc43.png">

- [x] login mit inaktivem Benutzer funktioniert trotzdem:
<img width="1071" alt="Screenshot 2020-06-18 at 13 15 34" src="https://user-images.githubusercontent.com/47860090/85014038-d87b6480-b165-11ea-833f-9b65914569a0.png">

- [x] getMyMfas is not implemented yet
