### ISSUE TITLE
Backend Bugs

### ISSUE THREAD

**Issue by peintnermax** [caos/zitadel#267]
- [x] OTP is based on userid, so its difficult to keep track with multiple users. (should preferably use a loginname) (#274 )

- [x] Error translation handler, add error id

- [x] editor on changes (https://github.com/caos/zitadel/pull/273)

- [ ] error on setup: pq: duplicate key value (org_id,domain)=('61245009726275865','caos-ag.zitadel.ch') violates unique constraint "primary"  (moved to #299 )
(I tried to solve this problem, but I dont have it anymore, @livio-a @adlerhurst can you reproduce it?) [(discussion)](https://github.com/caos/zitadel/issues/267#issuecomment-649410232)

- [x] changes: sort direction is asc instead of desc, add sortdirection as parameter (https://github.com/caos/zitadel/pull/273)

- [x] changes: query always returns the same list, no matter which offset is given (https://github.com/caos/zitadel/pull/273)

- [x] iam members (@fgerschwiler )

- [x] getOrgByDomainGlobal returns object not found (only domain is provided)

- [x] table names should be plural. `failed_event` should be `failed_events` (#287)

**Comment by adlerhurst** [comment]
I have the `violates unique constraint "primary"` on different tables. Each setup can produce a different error
e.g. my latest 2 setups:

1. in auth database
`ID=VIEW-AfC7G Message=unable to put object to view Parent=(pq: duplicate key value (id)=('6137067164454120261370668423315730SETUP') violates unique constraint "primary")`
2. in management database:
`ID=VIEW-AfC7G Message=unable to put object to view Parent=(pq: duplicate key value (org_id,user_id)=('61371117901709586','61371118304362770') violates unique constraint "primary")`
