### ISSUE TITLE
SAML IdP

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#2948]
As a customer, I want ZITADEL as SAML IdP, so that I can connect other applications with ZITADEL via SAML.

## Tasks

- [x] #2946 
- [ ] #3089
- [ ] #3090
- [ ] #3091
- [ ] #3092
- [ ] #3094

## SAML2.0 SPs we know customers are interested in

- [ ] Cohesity DataPlatform
- [ ] Rubrik CDM
- [ ] VMWare vCloud Director
- [ ] Citrix Netscaler in combination with Citrix Storefront
- [ ] AzureAD SSO (needs actions and additional configuration for the limited algorithms with SHA1)
- [ ] Google Workspace SSO
- [x] AWS SSO
- [x] Auth0 

@stebenz feel free to extend this list with your SPs
