### ISSUE TITLE
Console implement ui consistence

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#3024]
Depends on #3022 
The console should have a consistence in the elements over all ui elements.

**Acceptance criteria**
- [x] Consistence save mechanisms (implemented as designed in #3022 )
- [x] Consistence table behaviour (implemented as designed in #3022 )
- [x] Consistence in the navigation (implemented as designed in #3022 )
