### ISSUE TITLE
cli

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#3182]
As a user I want to interact with the zitadel server via cli. 

The commands depend on each other. If i execute `zitadel start` `setup` and `migrate` will be executed too.

## migrate (init)

`migrate` should prepare the minimal dependencies to start zitadel.

migrate depends on a cockroachdb. The database MUST be started before ZITADEL.

At the moment `eventstore.events`.

## setup (default data)

`setup` should initialise the default data.

### --local

initialise data insecure (http)

(CLI wizzard for encryption keys)

## start

`start` should run zitadel.  Prepare the storage for the projections and start them.

### --local

executes `setup` in local mode

## tenant

`tenant` should initialise a new tenant

(## update)

## TODOs:

- [ ] find names for server-cli and client-cli

## Acceptance criteria

- [ ] every user should be able to start zitadel within 5 minutes
- [ ] clear docs for the cli and configuration
- [ ] section in readme with getting started

**Comment by adlerhurst** [comment]
- [ ] init
  - [ ] database: zitadel 
  - [ ] schemas: projections, eventstore
  - [ ] tables: eventstore.events
  - [ ] sequences: evenstore.system_seq
- [ ] setup
  - [ ] simplify commands
  - [ ] create initial org
- [ ]  start
  - [ ] start zitadel
- [ ] start with init
  - [ ] execute all steps above
