### ISSUE TITLE
Changes for login page

### ISSUE THREAD

**Issue by juergrinaldi** [caos/zitadel#721]
Disclaimer: This changes are for optimzing the login area. Since most of the UI is represented by input fields and we have the material-design inputs on the console it doesn't make sense to make a consolidated design for login/console, as they will always look different. I still advice to use a regular styling for input fields on console. that said here are my suggestions for the changes:

Disclaimer 2: I don't have the overall view over the used color variables anymore :D take a variable that is next to the suggested color (or consulate me, if in doubt :)). this is for all the greyscale colors.

- [x] exclude the "Head" (h1, user-infos, lead text, etc.) from the form-max-with restriction and use approx. double the size for the head
- [x] Border Inputs: 1px #999999
- [x] Buttons: Border 1px
- [x] Standard font size: 16px
- [x] font size label: 0.8rem
- [x] h1 text-align: center
- [x] input fields: padding (left): 8px
- [x] password-complexity: margin-bottom: 0
- [x] TOS-Link: same size as text. (inline links should be same size as the text, tertiary buttons can be bigger)
- [ ] password confirmation: there needs to be an indicator why the 'next' button is greyed out when the passwords don't match
- [x] formfield checkbox label: text color as normal text (#282828 / #BBBBC8)
- [x] font-size user-login-name (head): 26px (fallback for long email-adresses on mobile? auto-shrink? flex?)
- [x] password invalid (EVENT-452ad): more approachable error message (in signal red)

**Light-Design**
- [x] disabled status not correctly displayed (greyed out, no 'pointer mouse',etc..)
- [x] hover secondary button: text #FFFFFF
- [x] primary button: text: #FFFFFF
- [x] checkmarks password complexity: color #50CA3D
- [x] default-user-icon: light
